### ISSUE TITLE
Regression in 3.2.0 / 3.2.1 - "ReferenceError: document is not defined"

### ISSUE THREAD

**Issue by Stanback** [paramaggarwal/react-dropzone#101]
I encountered this in an isomorphic app, I'm importing dropzone at the top of a component:
```
import Dropzone from 'react-dropzone';
```

However, when the Express server is executed, it returns `ReferenceError: document is not defined` for the following line:
```
var supportMultiple = document && document.createElement ? 'multiple' in document.createElement('input') : true;
```

I haven't looked at the changes that were introduced to know what the best solution is, however, since `document` doesn't exist in node, maybe the assignment to supportMultiple could be done in `componentDidMount` instead.

Moving back to =3.1.0 works for now

**Comment by okonet** [comment]
I was under impression that `document && document.createElement` should suffice for such check. Are you sure you're not using jsdom or something that mocks `document`?

**Comment by feesjah** [comment]
same problem here, I am using react-dom somewhere

**Comment by Stanback** [comment]
Someone else may be able to explain it better, but it seems that Node differs from browser JS engines in that it will throw a ReferenceError exception whenever an undeclared variable is encountered, even with a normal `if (document) ...` statement.

The typeof operator doesn't throw the exception... aside from moving the check to componentDidMount you could use something like this as a workaround:
```
const supportMultiple = (typeof document !== 'undefined' && document && document.createElement) ?
  'multiple' in document.createElement('input') :
  true;

 (typeof variable === 'undefined') {
    // variable is undefined
}
```

**Comment by feesjah** [comment]
@Stanback yes, this works indeed

**Comment by yargalot** [comment]
Just wanna chime in and say yeh just had this issue with the new release :+1:

**Comment by okonet** [comment]
@Stanback can you please submit a PR with the fix for node?

**Comment by Stanback** [comment]
@okonet Looks like @bruno12mota beat me to it: https://github.com/paramaggarwal/react-dropzone/pull/103

**Comment by bruno12mota** [comment]
Sorry @Stanback was needing it for Relax so decided to PR it :smile:

**Comment by okonet** [comment]
I'd like to see that fight in this one https://github.com/paramaggarwal/react-dropzone/issues/102 :facepunch:
