### ISSUE TITLE
multiple option with false value through props not working in 2.x

### ISSUE THREAD

**Issue by jitchavan** [paramaggarwal/react-dropzone#107]
Hi,
look like 2.x issue with curly bracket as i got somewhere in commits that for disabling multiple attribute as below:
multiple={false}

The above string works perfect but below string not working
 multiple="false"
multiple={this.props.multiple}

so looks like its curly bracket issue? below code does not throw error but also does not disable multiple upload.
```
return (
            <div>
                {this.state.files.length > 0 ? <div>
                <div>{this.state.files.map((file) => <img src={file.preview} style={{width:100}} /> )}</div>
                </div> : <Dropzone ref={this.props.id} onDrop={this.onDrop} multiple={this.props.multiple}>
                    <div>Try dropping some files here, or click to select files to upload.</div>
                </Dropzone>
                }
            </div>
        );
```

**Comment by okonet** [comment]
I'm not sure what's the issue. If you pass false without curly braces then it's a string.

**Comment by jitchavan** [comment]
using multiple="false" OR multiple={this.props.multiple}, multiple option not disabling for me.

**Comment by okonet** [comment]
> using multiple="false"

This is becuase you're passing a string instead of a boolean. You should pass `multiple={false}` or `multiple` for true.
