### ISSUE TITLE
Additional props

### ISSUE THREAD

**Issue by at0g** [paramaggarwal/react-dropzone#108]
It would be helpful if any additional props that are passed to the component are rendered on the root node, rather than being ignored.

For example:
- `tabIndex`
- `aria-*`
- `hidden`
- `title`
etc, etc

Should be really easy to implement using rest/spread ops.

```
// Known props that component handles specifically are extracted, 
// everything else is added to props
let { prop1, prop2, ...props } = this.props;
...
return (
    <div prop1={prop1} prop2={prop2} {...props}>
        ...
    </div>
);
```

**Comment by xabikos** [comment]
On top of that would be useful to render the id in the corresponding hidden input in order to connect it with a label.

**Comment by okonet** [comment]
Can you submit a PR?

**Comment by at0g** [comment]
> Can you submit a PR?

ok - will do
