### ISSUE TITLE
Handle folder drops recursively

### ISSUE THREAD

**Issue by InSuperposition** [paramaggarwal/react-dropzone#11]
When Dropping in a folder of files it treats the folder a 1 file. It would be nice if files and sub folders could be represented when one single folder is dropped in the drop zone. I'm not sure if this is a limitation of the HTML5 input file type or not.

**Comment by paramaggarwal** [comment]
Good idea, would be great if someone could submit a PR.

**Comment by InSuperposition** [comment]
The examples I have found, so far, only work in chrome.
I'll continue to look into it, I probably just need to dive into the API a bit more.
[Demo](https://html5-demos.appspot.com/static/dnd/all_types_of_import.html)
[Code](https://github.com/ebidel/html5demos/blob/master/html5-demos.appspot.com/static/dnd/all_types_of_import.html)

**Comment by paramaggarwal** [comment]
Looks like only Chrome 21+ ever implemented support for folders. No other browser supports it, so unlikely to be part of this library. Closing.

http://www.rajeshsegu.com/2012/08/html5-drag-and-drop-a-folder/

**Comment by jvanbrug** [comment]
@paramaggarwal @okonet I would love to be able to upload folders - does this change the reasoning behind not supporting folders? http://superuser.com/questions/909112/does-firefox-support-folder-upload

**Comment by okonet** [comment]
I believe we even have a JS only implementation for that in #174 but I might be wrong. Either way, I'd like some code issues be resolved before I merge, so help is appreciated.

**Comment by okonet** [comment]
Correction ↑: It still uses DOM API, so more investigation is needed I think.

**Comment by jvanbrug** [comment]
Great, let's move this conversation to #174

**Comment by jvanbrug** [comment]
and #134

**Comment by ArtemBernatskyy** [comment]
+1

**Comment by dejongch** [comment]
Any chance anything happened with this? I could really use the ability to either accept all files in a folder if it is dropped or somehow know it is a folder and not accept it at all.

**Comment by okonet** [comment]
There is a PR in progress https://github.com/react-dropzone/react-dropzone/pull/616
