### ISSUE TITLE
Is there a way to make the whole body a dropzone?

### ISSUE THREAD

**Issue by cheton** [paramaggarwal/react-dropzone#119]
I want the whole page to be droppable just like Dropzone's example:
https://github.com/enyo/dropzone/wiki/Make-the-whole-body-a-dropzone

Is there a way to do this by `react-dropzone`?

**Comment by okonet** [comment]
I assume this should be as easy as rendering the `<Dropzone>` at the top of your app and styling appropriately (i.e. remove all styles from it?)

**Comment by SylarRuby** [comment]
I agree with ^^

**Comment by cheton** [comment]
It did work! Thanks!
