### ISSUE TITLE
Only a single child?

### ISSUE THREAD

**Issue by marnusw** [paramaggarwal/react-dropzone#120]
Is there any specific reason why only a single child is allowed? 

```
children: React.PropTypes.element
```

I've been using Dropzones with multiple children in an older version for some time and never had issues. I can of course just wrap all children in a `span` or `div`, but since the Dropzone children render in its `div` it seems redundant.

**Comment by okonet** [comment]
You're right. There is no reason for that. Can you submit a PR that fixes this?

**Comment by marnusw** [comment]
I'll do that! Thanks.
