### ISSUE TITLE
Upload Progress?

### ISSUE THREAD

**Issue by approots** [paramaggarwal/react-dropzone#125]
Any way to display upload progress?

**Comment by approots** [comment]
I guess not really the scope of dropzone.

**Comment by okonet** [comment]
Right. Should be implemented in the userland.

**Comment by oeddyo** [comment]
Also need this feature. Any tips how shall I go and implement on my end? (new to react world)

**Comment by bbnnt** [comment]
hmm… no bad but i first expected to have the options/events promoted by dropzone.js. I might be wrong thinking it's related maybe
That is, where do you consider user land starts ?

**Comment by okonet** [comment]
This library tries to be minimal and composable. Dropzone.js tries to solve too many use cases with too many options.

**Comment by AVEmedia** [comment]
Ya but shouldn't there at least be a callback function that we can have access to in order to handle our own custom progress handling? I didn't see this callback listed.

**Comment by okonet** [comment]
No, why would this library be concerned about the uploading process? You should implement this yourself.

**Comment by approots** [comment]
@AVEmedia - You can register the "progress" event listener on an `XMLHttpRequest`.

    var xhr = new XMLHttpRequest();
    xhr.upload.addEventListener("progress", function(evt){
      if (evt.lengthComputable) {
        var percentComplete = evt.loaded / evt.total;
        console.log(percentComplete);
      }
    }, false);
    //...

Note that `fetch` doesn't support upload progress.

**Comment by heshamelmasry77** [comment]
so how you implemented it

**Comment by rolandjitsu** [comment]
@heshamelmasry77 please use SO for such questions as this sort of functionality is not handled by this lib.
