### ISSUE TITLE
Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by greenlaw110** [paramaggarwal/react-dropzone#15]
I tried to this component but end up with error:
![image](https://cloud.githubusercontent.com/assets/216930/7179112/ecb4a9ae-e477-11e4-8a2f-a94badc63c36.png)

Here is my code:

```javascript
var Dropzone = require('react-dropzone');

var PfUpload = React.createClass({
	render: function () {

		var style = {
			backgroundImage: "url(" + this.props.img + ")",
			position: 'relative'
		};

		if(this.props.editing) {
			return (
				<div id="pf-upload" style={style}>
					<Dropzone onDrop={this._onDrop} size={42}>
					</Dropzone>
				</div>
			);
		}

		return (
			<div id="pf-upload" style={style}>
			</div>
		);
	},

	_onDrop: function(file) {
		console.log(file);
	}
});

module.exports = PfUpload;
```

**Comment by paramaggarwal** [comment]
I'm unclear about the issue you are facing. Can you try the suggestion in the error message?

**Comment by PhilipBrady13** [comment]
i am having the same issue. i am running react 0.14.2 with react-dropzone 3.0.0. I am not adding any refs myself, and when I remove the Dropzone component the error goes away so its origin is the Dropzone component. i have checked for multiple versions of react using "npm ls react" and got 
"`-- react@0.14.2". i deleted node_modules folder and reinstalled as well but no luck. any suggestions would be awesome
