### ISSUE TITLE
Add test for IE8+ browser compatibility

### ISSUE THREAD

**Issue by fricke** [paramaggarwal/react-dropzone#17]
Just curious to see if there have been tests on the various browsers w/ this package... mainly for IE.

**Comment by paramaggarwal** [comment]
Nope, hasn't been tested across multiple browsers. Unfortunately this component is missing tests too.

**Comment by eventhough** [comment]
@paramaggarwal @fricke The File API doesn't work in IE9 or IE8.

http://caniuse.com/#feat=fileapi

Do you think it would be possible to add compatibility support for things like filesize? 

http://stackoverflow.com/questions/1832415/how-validate-file-size-using-html-and-javascript-on-client-side

**Comment by paramaggarwal** [comment]
Thanks @eventhough - so this library is IE10+.
