### ISSUE TITLE
Allow custom attributes for file input

### ISSUE THREAD

**Issue by mikemintz** [paramaggarwal/react-dropzone#20]
For the file input, I'd like to be able to not have "multiple" set to true, and to configure the "accept" attribute. It would be nice to pass those attributes down in props.

**Comment by joaosamouco** [comment]
:+1: This would be nice. And not so hard to implement.

**Comment by fraserxu** [comment]
Sending a pull request!

**Comment by matiaslarsson** [comment]
Added pull request #29 to support setting multiple to false as @mikemintz also wished.
