### ISSUE TITLE
trying to add the same file again does nothing

### ISSUE THREAD

**Issue by flogball00** [paramaggarwal/react-dropzone#35]
When i try to add the file to the dropzone again, my ondrop doesnt do anything.  Even in the demo, the received files doesnt change

**Comment by velveteer** [comment]
Looks like this commit will resolve it: https://github.com/paramaggarwal/react-dropzone/commit/8bcf347f8f1b5dd6c8ad2498b978772e3ff351dc

@paramaggarwal Will we be seeing a new release soon?

**Comment by paramaggarwal** [comment]
Yes, this is fixed in #41 and published to npm as `v1.2.2`.

**Comment by paramaggarwal** [comment]
Yes, this is fixed in #41 and published to npm as `v1.2.2`.
