### ISSUE TITLE
onDrop does not fire unless adding `e.stopPropagation()` or `return false` to `onDragOver`

### ISSUE THREAD

**Issue by vjpr** [paramaggarwal/react-dropzone#37]
I had to modify the `onDragOver()` to get it to work.

I am using Chrome `Version 45.0.2426.0 canary (64-bit)`

It seems like its common practice from this post: http://stackoverflow.com/a/9319200/130910

**Comment by hudakdidit** [comment]
I can confirm this also. Using Chrome Version 43.0.2357.132 (64-bit)

**Comment by paramaggarwal** [comment]
Please raise PR, I'll merge.

**Comment by hudakdidit** [comment]
https://github.com/paramaggarwal/react-dropzone/pull/45 Thanks!

**Comment by paramaggarwal** [comment]
Merged, thanks!

**Comment by nicosoap** [comment]
Ok
