### ISSUE TITLE
Export the transpiled JS instead of the ES6

### ISSUE THREAD

**Issue by idolize** [paramaggarwal/react-dropzone#38]
Related to #14 

Currently, with the latest published version on npm, I cannot `require` and use this module (I get the following error: `Cannot find module 'reactify' from 'node_modules/react-dropzone'`).

Looking more closely, it appears the `reactify` Browserify transform is listed in the `package.json` (recently changed to `babelify` on master branch, but the same issue persists).

This error is then caused because `reactify` (now `babelify`) is not listed in the `dependencies` section anywhere, so `npm install` does not install it and thus Browserify can't run the transform.

This in and of itself is an issue, but the bigger issue is that the module is requiring the consumer to perform any transpilation. Instead, the source should be transpiled **before** publishing to npm so that no extra build step is required for the consumer of the library.

See [this StackOverflow question](http://stackoverflow.com/q/13645824) for more information; the general guidance is to create a separate location for your compiled code (which is optionally added to `.gitignore`), add your source code to `.npmignore`, and then add the compile step to the [`prepublish` hook](https://docs.npmjs.com/misc/scripts) in your `package.json` to automate the whole thing.

----
**Edit:** In my original post I assumed Babel was being used to transpile the core component source, but I see now it is only used for the demo page. In that case the demo page should have it's own `package.json` which handles this so the core project can remain pure—otherwise this issue is going to persist.

**Comment by idolize** [comment]
From the [Browserify docs](https://github.com/substack/node-browserify#browserifytransform):

> Now (that you have added a transform field to package.json) when somebody require()s your module, (the transform) will automatically be applied to the files in your module without explicit intervention by the person using your module.

Is this really necessary here?

**Comment by paramaggarwal** [comment]
@idolize Excellent thoughts.

**Comment by paramaggarwal** [comment]
Going to leave this open, I would ideally like to use JSX in index.js, and then publish transpiled code on npm.

**Comment by paramaggarwal** [comment]
`v2.0.1` introduces babel with `npm run build`.

**Comment by crobinson42** [comment]
+1 for publishing/shipping consumable module to `npm`. Run the build then publish to npm. 

@paramaggarwal I'm curious why this isn't the case already?

**Comment by okonet** [comment]
https://github.com/okonet/react-dropzone/issues/112
