### ISSUE TITLE
README misleading

### ISSUE THREAD

**Issue by djkirby** [paramaggarwal/react-dropzone#49]
> If no style or className properties are defined, the style object will default to the **width and height properties** (or 100px if they aren't defined) along with a borderStyle of "solid" or "dashed" depending on if drag actions are taking place.

It doesn't seem you can actually specify `width` or `height` props:
``` javascript
  propTypes: {
    onDrop: React.PropTypes.func.isRequired,
    size: React.PropTypes.number,
    style: React.PropTypes.object,
    supportClick: React.PropTypes.bool,
    accept: React.PropTypes.string,
    multiple: React.PropTypes.bool
  },
```
`this.props.width` and `this.props.height` aren't used at all in the source.

As a solution I've passed `style={{width: N, height: N}}` but by doing so that doesn't set the borderStyle appropriately. Since I've supplied a `style` prop it is ignoring the borderStyle here.
``` javascript
var style = this.props.style || {
    width: this.props.size || 100,
    height: this.props.size || 100, 
    borderStyle: this.state.isDragActive ? 'solid' : 'dashed'
};
```
I guess that is expected based on the quoted section of the README above but I don't think it's preferable since it's not really possible to recreate the borderStyle when dragging over using `style`.

Also the docs don't mention the `supportClick`, `accept`, or `multiple` properties.

**Comment by paramaggarwal** [comment]
The discrepancy you are seeing is because this was added very recently here: https://github.com/paramaggarwal/react-dropzone/blob/master/index.js#L22-L23. This change is on `master` and not published to npm yet. Hence your code does not have this. 

I just published `v1.2.3` to npm with the latest from master.

**Comment by djkirby** [comment]
Gotcha thanks for the quick response!

It would be nice, though, for the README to mention the `supportClick`, `accept`, and `multiple` props. I can try to update later when I get some free time.

**Comment by paramaggarwal** [comment]
Yes there are a few things I want to touch up on this repo. Will leave this open.

**Comment by paramaggarwal** [comment]
Merged, thanks!
