### ISSUE TITLE
dragging a file on to the component throws errors in IE

### ISSUE THREAD

**Issue by tikotzky** [paramaggarwal/react-dropzone#58]
you get an error of `Unexpected call to method or property access.`
the error is happening [here](https://github.com/paramaggarwal/react-dropzone/blob/133f7ceafd1e9f011c49f022a76aa47e92254e30/index.js#L51)

It seems like IE only allows you access that property in the `onDragStart` event.

you can try a demo here: http://output.jsbin.com/vanulay

**Comment by paramaggarwal** [comment]
Could you submit a PR? I don't have IE to look into this...

**Comment by tikotzky** [comment]
I'm trying to understand what [this block](https://github.com/paramaggarwal/react-dropzone/blob/133f7ceafd1e9f011c49f022a76aa47e92254e30/index.js#L49-L56) of code is doing.

I see it came from [here](https://github.com/paramaggarwal/react-dropzone/pull/48) but I'm sure exactly why its needed.

**Comment by paramaggarwal** [comment]
`v2.0.1` removes any reference to `dropEffect` and `effectAllowed` as they don't work consistently across browsers.
