### ISSUE TITLE
brackets dont match

### ISSUE THREAD

**Issue by mitselek** [paramaggarwal/react-dropzone#6]
Hi,
Is it only me or there are really unbalanced brackets in sample code.
And how on earth it is working here on github in read.me file?

I don't even dare to ask about the magic that lets HTML in render function to return successfully (no quoting?).

```js
var component = React.createClass({

  fileHandler: function(file) {
      uploadScript(file, uploadURL, function(err, res) {
        if (res.code == 200) {console.log("Upload success.")}
      });
    }
  },

  render: function() {
    return (
      <div>
        <Dropzone handler={this.fileHandler} size={200} message="Drag and drop a file here"/>
      </div>
    );
  }
});
```

**Comment by paramaggarwal** [comment]
It's not HTML, it's called [JSX](http://facebook.github.io/react/docs/jsx-in-depth.html).

**Comment by mitselek** [comment]
And what about not matching brackets?

**Comment by paramaggarwal** [comment]
Fixed, sir.

**Comment by mitselek** [comment]
Cool,
Thanks, i will try it out.
Im still puzzled about it working fine in github's read.me, tho :s
