### ISSUE TITLE
Possible typo in onDragEnter

### ISSUE THREAD

**Issue by micsumner** [paramaggarwal/react-dropzone#68]
I'm getting errors on this line in the onDragEnter function:

```javascript
var dataTransferItems = Array.prototype.slice.call(e.dataTransfer ? e.dataTransfer.items : e.target.files);
```

because e.dataTransfer.items is undefined. I believe this is supposed to read ```e.dataTransfer.files``` to match up with the rest of the usages. 

For reference here's the mozilla documentation on the DataTransfer object: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer

**Comment by micsumner** [comment]
I believe this bug was introduced in commit d4d0867

**Comment by paramaggarwal** [comment]
Yes, you are right. @okonet could you please help out?

**Comment by okonet** [comment]
Well, funny thing is that in Chrome it is `items`. I'll check for either one is defined.

**Comment by micsumner** [comment]
Ah, yep, I found this on Safari and Firefox.
