### ISSUE TITLE
click dropzone to browser for file from filesystem

### ISSUE THREAD

**Issue by Pomax** [paramaggarwal/react-dropzone#7]
file drop is super useful, but it can be made even better by giving the dropzone a "click to open a file dialog for file selection", to effect a "file drop" that way.

**Comment by paramaggarwal** [comment]
This was introduced in PR #4, but I haven't gotten around to updating the README to reflect the change.

**Comment by Pomax** [comment]
really? nice! Is adding a `handleClick` handler enough to get things working? (looking over the PR, don't have anything beyond a tablet available atm to try running code)

**Comment by Pomax** [comment]
ah, based on https://github.com/paramaggarwal/react-dropzone/pull/4/files#diff-168726dbe96b3ce427e7fedce31bb0bcR36 it looks like it might be worth changing the selector to:
```
var node = e.target.querySelector("input[type=file]");
```
just to make sure the selection is guaranteed for a type="file" input rather than "any" input.

Also probably better to replace https://github.com/paramaggarwal/react-dropzone/pull/4/files#diff-168726dbe96b3ce427e7fedce31bb0bcR96 with a style that's simply `display: "none"` rather than trying to move it off screen. Especially since `position: "absolute"` is actually *relative* to the first ancestor with an explicit positioning so that input element might be entirely visible on-page with this CSS =)

Final note: no need for the replacement in https://github.com/paramaggarwal/react-dropzone/pull/4/files#diff-168726dbe96b3ce427e7fedce31bb0bcR102 - in fact, since this isn't a submittable form, that should *definitely* stay a div (input elements don't need a form around them, and in this case the form element is actually semantically incorrect).

Hopefully I have some time to write a PR for on top of this soon (although if you get to it before I do, hurray =)

**Comment by paramaggarwal** [comment]
Closing as this is fixed.
