### ISSUE TITLE
Active class disappears when drag over children

### ISSUE THREAD

**Issue by yoni-tock** [paramaggarwal/react-dropzone#75]
Looks like it's [this issue](http://stackoverflow.com/questions/7110353/html5-dragleave-fired-when-hovering-a-child-element). If I have time I'll open a PR to fix it. We're causing this with just the following code

```jsx
<Dropzone className='dropzone-component' activeClassName='dropzone-component__active'
  onDrop={this.onUploadHero} size={150}>
  Upload Background Image
</Dropzone>
```

**Comment by okonet** [comment]
I've solved this by adding a CSS `pointer-events: none`. Probably this should be done by the lib itself...

**Comment by yoni-tock** [comment]
Brilliant! Worked for me too

**Comment by okonet** [comment]
#73

**Comment by yoni-tock** [comment]
:+1:

**Comment by tony99nyr** [comment]
Can we get a `npm version patch` `npm publish` with this fix please? xD

**Comment by paramaggarwal** [comment]
Done. npm `v2.2.1`.
