### ISSUE TITLE
Active class doesn't appear in Firefox

### ISSUE THREAD

**Issue by yoni-tock** [paramaggarwal/react-dropzone#76]
I wasn't able to diagnose the issue's root cause, but I can't get the active class to appear at all. Maybe it's because you need to `preventDefault` on the nativeEvent as well? Firefox seems to have strict rules about what counts as a valid drop target.

**Comment by seyar** [comment]
same issue on chrome 48 on Mac

**Comment by seyar** [comment]
Solved. @yoni-tock specify ```accept``` and ```className``` param.
