### ISSUE TITLE
Upgrade to React 0.14 and release a new major version

### ISSUE THREAD

**Issue by okonet** [paramaggarwal/react-dropzone#80]
Discussion already has been starter in #77 but I think it's easier to track as a separate issue.

My suggestion would be

1. [ ] Upgrade the code to React 0.14
1. [ ] Release a new major version 3.0 of the package
1. [ ] Leave the 2.x as a maintenance branch for React 0.13 support

WYT?

**Comment by paramaggarwal** [comment]
Sounds good. Thanks a lot for all the help here. I added you as a contributor so that I don't slow you down. :)

**Comment by okonet** [comment]
Thanks! I'll try to commit something this week.

**Comment by bobiblazeski** [comment]
Glad  to hear that you plan upgrade soon.
I've just upgraded to 0.14.0 and I got below warning
Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead. 
beside that components seems to works well.

**Comment by okonet** [comment]
Yes, it will work with React 0.14 but this warnings are annoying. Thing will get broken by next release.

**Comment by willdady** [comment]
+1

**Comment by ekonstantinidis** [comment]
Any updates on this one? Thanks for the awesome work so far :smile:

**Comment by okonet** [comment]
#84

**Comment by ekonstantinidis** [comment]
Thanks @okonet ! Works great! No more warnings :+1:

**Comment by okonet** [comment]
We should thank @kumarharsh for that. 👏

**Comment by bobiblazeski** [comment]
Warning is gone many  @kumarharsh

**Comment by kumarharsh** [comment]
:D
