### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined if prop assept setted

### ISSUE THREAD

**Issue by IndexOf** [paramaggarwal/react-dropzone#81]
if in component set param accept, when user drops file into dropZone returns exception
http://screencast.com/t/VCM8DHhWGfds

<Dropzone
            onDrop={this.props.onDrop}
            className={className}
            accept=".docx"
            disableClick="true" ref="dropzone"
            activeClassName="dropzone_active_yes"
>

**Comment by okonet** [comment]
What browser are you using? Also what kind of file?

**Comment by IndexOf** [comment]
file *.docx, browser chrome build 46

**Comment by okonet** [comment]
Please install the latest version. It should be fixed by now.

**Comment by okonet** [comment]
Reopen if it's not.
