### ISSUE TITLE
State based classNames require className

### ISSUE THREAD

**Issue by jking90** [paramaggarwal/react-dropzone#88]
For `activeClassName` or `rejectClassName` to work, `className` must be set.

**Comment by okonet** [comment]
So what's the issue here?

**Comment by jking90** [comment]
It seems clunky to require `className` to use `activeClassName`. I don't need a generic `className` on my implementation, just an `activeClassName`.

**Comment by paramaggarwal** [comment]
@jking90 Open for PRs!

**Comment by okonet** [comment]
Sounds legit. Please submit a PR!
