### ISSUE TITLE
string style ref causes ref error in certain implementations

### ISSUE THREAD

**Issue by brandonhill** [paramaggarwal/react-dropzone#91]
The legacy (string) style of ref is causing a ref error when implementing in a nested and component-passed-as-props fashion. Updating to the callback style of ref fixes the error:

change line 115 to: `var fileInput = this._fileInput;`

change line 180 to: `ref={_ => this._fileInput = _}`

I tried to make a pull request but couldn't.

**Comment by okonet** [comment]
Why couldn't? What was the problem with submitting a PR?
