### ISSUE TITLE
Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

### ISSUE THREAD

**Issue by tkiethanom** [paramaggarwal/react-dropzone#94]
Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

**Comment by okonet** [comment]
Please provide more info and exact issue you're having. Also, which version you are using. Just pasting output isn't very helpful here.

**Comment by tkiethanom** [comment]
This deprecation warning appears in the console because I believe the function was moved to ReactDOM in the latest version of React v0.14.

**Comment by okonet** [comment]
Which version are you using?

**Comment by tkiethanom** [comment]
I was using v2. This is resolved by updating to v3. Sorry for the issue.
