### ISSUE TITLE
Filter by file types on dialog open

### ISSUE THREAD

**Issue by bobiblazeski** [paramaggarwal/react-dropzone#99]
Is it possible to filter files when Dialog is open, I would like user to see only image files: png & jpg.

**Comment by okonet** [comment]
Yes, use `accept` prop to pass desired MIME types according to http://www.w3.org/TR/html-markup/input.file.html

**Comment by okonet** [comment]
README should inform about it

**Comment by bobiblazeski** [comment]
Works great, many thanks.
